spring:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.example.bean
  configuration: